version: '3'
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  ui-test:
    build:
      context: .
      dockerfile: Dockerfile.dev    
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    
